### PR TITLE
Add search IOQ metric

### PR DESCRIPTION
**Pull request by nickva**

### CODE REVIEW

**Comment by jiangphcn** [comment]
@nickva thanks. Are there corresponding changes on dreyfus or metrics repo?

**Comment by jiangphcn** [comment]
also, found https://github.com/cloudant-labs/dreyfus/blob/master/priv/stats_descriptions.cfg#L55-L59 in dreyfus repo

**Comment by nickva** [comment]
@jiangphcn ah good, call. Those should go in dreyfus. I but there they need to be the right metric. Instead of `[couchdb, io_queue2, search, count]` maybe `[couchdb, io_queue, search]` and `[couchdb, io_queue2, search]`?

**Comment by jiangphcn** [comment]
yes, make sense, @nickva. I will create one PR in drefyus to address this.

**Pull request closed without merging**
